[build]
target = "valida-unknown-baremetal-gnu"

[target.valida-unknown-baremetal-gnu]
linker = "/valida-toolchain/bin/ld.lld"
rustflags = [
    "-C", "link-arg=/valida-toolchain/ValidaEntryPoint.o",
    "-C", "link-arg=/valida-toolchain/io.o",
    "-C", "link-arg=--script=/valida-toolchain/valida.ld",
    "-C", "link-arg=/valida-toolchain/lib/valida-unknown-baremetal-gnu/libc.a",
    "-C", "link-arg=/valida-toolchain/lib/valida-unknown-baremetal-gnu/libm.a",
]

[env]
CC_valida_unknown_baremetal_gnu = "/valida-toolchain/bin/clang"
CFLAGS_valida_unknown_baremetal_gnu = "--sysroot=/valida-toolchain/ -isystem /valida-toolchain/include"
