[workspace]
[package]
version = "0.1.0"
name = "fibonacci-script"
edition = "2021"

[dependencies]
sp1-sdk = { git = "https://github.com/succinctlabs/sp1.git", tag = "v3.0.0" }

[build-dependencies]
sp1-build = { git = "https://github.com/succinctlabs/sp1.git", tag = "v3.0.0"  }